name: Olly Hermon-Taylor
favicon: null
layout_spectrum: 0.61453
typography_spectrum: 0.34575721621513367
title: Olly Hermon-Taylor Coaching For Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#081110'
    - '#d5dbd7'
    - '#3d3d26'
    - '#a6a7a1'
  brandStrength: 0.02278648759238422
  lightness: 0.8432647129520774
  saturation: 0.015053452458232641
  rhythmicContrast: 0.49634562712162733
purpose: []
