name: Olly Hermon-Taylor
favicon: null
layout_spectrum: 0.618258819449693
typography_spectrum: 0.34575721621513367
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.02278648759238422
  lightness: 0.8432647129520774
  saturation: 0.015053452458232641
  rhythmicContrast: 0.49634562712162733
purpose: []
